---

apiVersion: databases.schemahero.io/v1alpha4
kind: Database
metadata:
  name: my-db
spec:
  immediateDeploy: true
  connection:
    postgres:
      host:
        valueFrom:
          secretKeyRef:
            name: my-db
            key: endpoint
      user:
        value: masteruser
      password:
        valueFrom:
          secretKeyRef:
            name: my-db
            key: password
      port:
        value: "5432"
      dbname:
        value: my-db

---

apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  name: videos
spec:
  database: my-db
  name: videos
  schema:
    postgres:
      primaryKey:
      - id
      columns:
      - name: id
        type: text
        constraints:
          notNull: true
      - name: title
        type: text
        constraints:
          notNull: true
